# VORO package

include(ExternalProject)

set(VORO_SOURCE_DIR ${MAIN_SOURCE_DIR}/voro)
set(VORO_BINARY_DIR ${MAIN_BINARY_DIR}/voro)
set(VORO_INSTALL_PREFIX ${MAIN_INSTALL_PREFIX}/voro)

message(STATUS "Install VORO last commit on main on 4/3/2026")
message("Installing voro in ${VORO_INSTALL_PREFIX}")

ExternalProject_Add(VORO
    GIT_REPOSITORY https://github.com/chr1shr/voro
    GIT_TAG b0dac575a47af0f90b5b100e6dc199a493c7cb83 # main on 4/3/2026
    GIT_SHALLOW TRUE
    GIT_PROGRESS TRUE
    SOURCE_DIR ${VORO_SOURCE_DIR}
    BINARY_DIR ${VORO_BINARY_DIR}
    CMAKE_ARGS -DVORO_BUILD_CMD_LINE=OFF -DVORO_BUILD_EXAMPLES=OFF -DVORO_ENABLE_DOXYGEN=OFF -DCMAKE_INSTALL_PREFIX=${VORO_INSTALL_PREFIX} -DCMAKE_POSITION_INDEPENDENT_CODE=ON
)
